services:
  app:
    image: ${DOCKERHUB_USERNAME:-local}/project-sem-1:latest
    build: .
    ports:
      - "${APP_PORT:-8080}:8080"
    environment:
      - APP_DB_HOST=${APP_DB_HOST:-database}
      - APP_DB_PORT=${APP_DB_PORT:-5432}
      - APP_DB_NAME=${APP_DB_NAME:-project-sem-1}
      - APP_DB_USER=${APP_DB_USER:-validator}
      - APP_DB_PASSWORD=${APP_DB_PASSWORD:-val1dat0r}
      - APP_PORT=${APP_PORT:-8080}
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:17
    environment:
      - POSTGRES_DB=${APP_DB_NAME:-project-sem-1}
      - POSTGRES_USER=${APP_DB_USER:-validator}
      - POSTGRES_PASSWORD=${APP_DB_PASSWORD:-val1dat0r}
    ports:
      - "${APP_DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${APP_DB_USER:-validator} -d ${APP_DB_NAME:-project-sem-1}"]
      interval: 5s
      timeout: 5s
      retries: 5
